### ISSUE TITLE
Unable to save stock value for variation product. 

### ISSUE THREAD

**Issue by royrakesh** [weDevsOfficial/dokan#1034]
Hi 
When trying to update the stock of a variation product it's not saving.
This field always save as 0 when saving the product http://prntscr.com/wjjpyu

But I can save the stock at variation label.
I think this box should be hidden if the product is variable  http://prntscr.com/wj0kbx

In your code `https://github.com/weDevsOfficial/dokan/blob/develop/templates/products/inventory.php`

line 13 to 26. on the line 18 the class should be `hide_if_variation` not `hide_if_variable`.

  ```
<div class="content-half-part dokan-form-group hide_if_variation">
            <label for="_sku" class="form-label"><?php esc_html_e( 'SKU', 'dokan-lite' ); ?> <span><?php esc_html_e( '(Stock Keeping Unit)', 'dokan-lite' ); ?></span></label>
            <?php dokan_post_input_box( $post_id, '_sku' ); ?>
        </div>

        <div class="content-half-part hide_if_variable">
            <label for="_stock_status" class="form-label"><?php esc_html_e( 'Stock Status', 'dokan-lite' ); ?></label>

            <?php dokan_post_input_box( $post_id, '_stock_status', array( 'options' => array(
                'instock'     => __( 'In Stock', 'dokan-lite' ),
                'outofstock'  => __( 'Out of Stock', 'dokan-lite' ),
                'onbackorder' => __( 'On Backorder', 'dokan-lite' ),
            ) ), 'select' ); ?>
        </div>
```

**Can the user save stock at the main level when the product is a variable product?** http://prntscr.com/wj0kbx

**Comment by kapilpaul** [comment]
@royrakesh 

as woocommerce giving the option for saving stock at the main level so we are keeping this.

ref: https://prnt.sc/x77ylr

**Comment by royrakesh** [comment]
Yes, I also want that option but it's not saving properly when product is a variable product.

**Comment by ecottles** [comment]
Hello, 

Two years ago I tried to convey this same issue without success. The issue is real and continues to persist.
Expatiation:
Woocommerce behavior when the input values are set in the inventory panel, said values are applied to each variation created when the action is triggered. This behavior is non existent in the dokan variations editor.

Within the variations editor in dokan the action "create variations from attribute" is supposed to get the input values from the inventory panel if the values are set. And apply the values to each variation created.

But It Doesn't'. The code needs to be tweaked a little to replicate Woocommerce default behavior.

Good Day

**Comment by alamgircsebd** [comment]
Resolved
