### ISSUE TITLE
[Question] How admin_commission handle coupons ?

### ISSUE THREAD

**Issue by o-Chamie-o** [weDevsOfficial/dokan#1131]
Hi,

I cannot find where is handle the coupon in the commision price.

For instance : 
I have a product with a fixed commission.
Then I add a coupons for this product.
I apply the coupon, complete the order.
And a commision rate is applied but I don't understand how ?

Can you provite some explaination on this feature, and where can I hook this to apply a custum admin commision, based on (baseprice - coupon)

Thank you

**Comment by tanjiralmamun** [comment]
Hi @o-Chamie-o,

By default, Dokan calculates the admin commission based on the actual product price, excluding the tax & shipping fee. Right now, Dokan calculates the admin commission after applying the coupon/discount.

Since a coupon reduces the product price, the admin commission will be calculated from the discounted/reduced product price.

Let's say, a product price is **$100**. Here the admin commission is **$10**. You're giving a **10% discount/coupon** code. After applying the coupon, the product price is **($100 * 0.1) = $90**.

Now, the product price is **$90**, and the admin commission will deduct from that discounted amount. So, the vendor earnings will be **($90 - $10) = $80**.

Thank you!

**Comment by o-Chamie-o** [comment]
Thanks for your respond.

Can you show me where this is handled in the code please ?

**Comment by nurul-umbhiya** [comment]
@o-Chamie-o 
1. Vendor Coupon: https://wedevs.com/docs/dokan/vendor-dashboard/coupons-2/
2. Admin/Marketplace Coupon: https://wedevs.com/docs/dokan/tutorials/how-to-create-coupons-for-vendors/
