### ISSUE TITLE
Tax calculates incorrectly on the cart/checkout page and parent orders

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1207]
**Description of the Bug:**
If different vendors have different tax classes and each tax class applied to shipping, then Tax calculates incorrectly on the cart/checkout page and parent order.

But it shows the correct result on the sub-orders.

**_Video URL:_** https://share.vidyard.com/watch/GyRNNNG9GYEfGT6XAqqKDZ?

**How to reproduce:**
- Keep Shipping tax class setting to Shipping tax class based on cart items
- Set different tax class for different vendors products
- Add cart product from different vendors
- The shipping tax isn't calculating correctly cart/checkout page and parent orders
- Check sub-orders, it shows the correct calculation

**Expected Behavior:**
Tax should calculate correctly on the cart/checkout page and parent orders

**System Status:**
Dokan Lite: v3.2.6
Dokan Pro: v3.2.5
WordPress: v5.7.2
WooCommerce: v5.3.0

**Comment by nurul-umbhiya** [comment]
@shanjidah is this issue still valid?

**Comment by shanjidah** [comment]
@alamgircsebd please review this scenario. This issue is valid but I find the wrong calculation on the parent order total. 
The order total amount should be 274.05 but the total amount shows 274.
**Here is the screenshot please review .**
<img width="782" alt="Screen Shot 2021-07-15 at 2 35 12 PM" src="https://user-images.githubusercontent.com/37714632/125756905-eb66e780-04ee-45c9-9efb-32a58c748b67.png">
<img width="854" alt="Screen Shot 2021-07-15 at 2 33 11 PM" src="https://user-images.githubusercontent.com/37714632/125757019-d9abaf56-c3cc-4a24-b1aa-52f255e484f0.png">

**Comment by alamgircsebd** [comment]
Already resolved
