### ISSUE TITLE
set limitation for how many product tags that vendor can input

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1236]
There is no limits for how many tags that vendor can input, vendor can input endless tags for their product,  this will create mess on the system and no good for the filtering.  setting for how many tags that vendor can input for each of the product is kind  of essential.

**Comment by Tangol** [comment]
I strongly support this.

Look what happens when you don't set limits to this system:
![tags](https://user-images.githubusercontent.com/3336728/121525503-191c5f80-ca01-11eb-89dd-0e0927ca5819.png)

And I could have kept going...

If such a system is hard to implement, as a quick solution I would hardcode a max number of **5 tags** that can be added per product (eg.: `Apple` `iPhone` `12 Pro` `Red` `Brand New`).
I believe **5** is a good number as you want to constrain vendors to be creative and specific in their keyword use.

**Comment by leew999** [comment]
yes, we need 2 things for this.

1: setting for how many tags that vendor can enter
2: setting for description text which telling vendor how many tags they can enter

**Comment by Tangol** [comment]
I have given some more thought on this matter and I've just realized that this is a **HUGE** issue as vendors will exploit the tags system in order to link their product to as many tags as they can (even irrelevant ones), in order to have the customer see their product everywhere.

For example, you'll have a vendor link their Samsung TV listing, to a LG TV tag, so when the customer clicks on the LG tag, he will also see the Samsung listing...
Major problem.

**Comment by leew999** [comment]
the basic setting for the limitation and the description is fundamental for this, in my experience, vendor can enter whatever you can't imagined into the system, lots people will enter things like "#abc #bbc #abcd #123"... this is the result because there is no description for the field.
