### ISSUE TITLE
Shipping tax goes to the Tax Fee Recipient when the Shipping Fee Recipient is different

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1384]
**Description of the Bug:**
If the Shipping Fee Recipient is the Admin and Tax Fee Recipient is the Vendor, then the Shipping Tax adds to the Vendor Earnings instead of Admin Commission.

**How to reproduce:**
- Set Admin as the Shipping Fee Recipient
- Set Vendor as theTax Fee Recipient
- Make an order
- Check Vendor Earnings and Admin Commission to see the difference.

**Expected Behavior:**
Shipping tax should go to the respective shipping fee recipient.

**System Status:**
Dokan Lite: v3.2.15
Dokan Pro: v3.3.9
WordPress: v5.8.1
WooCommerce: v5.8.0

**Comment by Aunshon** [comment]
Assalamulaikum vaiia,
I have tested and tried to reproduce this issue but couldn't.

I have set - Shipping Fee Recipient -> Admin
I have set - Tax Fee Recipient -> Vendor

When i make an order admin gets the shipping fee with commission and vendor get the tax. 
Its working on my end.

**Testing the issue on:**
Dokan Lite: v3.3.0
Dokan Pro: v3.4.0
WordPress: v5.8.1
WooCommerce: v5.8.0

Vaiia please let me know this issue is still in the latest version of dokan, if exists please give me a video it would be very helpfull.

**Comment by janiperkio** [comment]
> Assalamulaikum vaiia, I have tested and tried to reproduce this issue but couldn't.

Hello @Aunshon, I'm the customer who issued this bug report. The issue is with shipping tax, not product tax.

To reproduce the issue, please follow the steps @tanjiralmamun indicated, but in addition create a shipping method, set this shipping method "Tax status" as "Taxable", set a shipping cost other than 0 and create order using this shipping method. Now the _shipping_ tax goes to the vendor, but the shipping tax must go to the admin since he is the one who is receiving the delivery funds.

The use case for us is that the vendor sells the products (so he receives the product fee and _product_ tax), and we deliver the products (so we should receive the shipping fee AND _shipping_ tax). Now all tax is bundled and sent to vendor in this case, which makes the tax income and calculations go wrong.

Hopefully this helps to describe the issue in hand.

**Comment by shohag121** [comment]
@Mohaiminulislam1989 Bhaya, Please share your thoughts on this issue.

**Comment by shohag121** [comment]
Hello @janiperkio,

To resolve the issue, we need some additional information. Would you please help us by providing some information needed?

**Info needed:**
* Payment Gateway used
* Country of business
* Tax policy
* Who is Marketplace Taxpayer
