### ISSUE TITLE
Hide the "Downloadable Product Permission" option from the non-downloadable products order page

### ISSUE THREAD

**Issue by Anower16** [weDevsOfficial/dokan#1428]
**Description**
Generally, The Downloadable Product Permission field/box always displays to every order whether the product is downloadable or non-downloadable. For convenience, here is a [screenshot](https://nimb.ws/8uoIWV).

**How to reproduce**
From a vendor dashboard, edit an order and scroll down and you will find the **Downloadable Product Permission**. 

**Possible Output**
It would be better if the non-downloadable products orders don't show the Downloadable Product Permission box.

**Environment**
Dokan 3.3.1

**Comment by rajankarmakar** [comment]
Hiding and showing downloadable panel on the product page has a checkbox. With the checkbox, you can toggle the checkbox as required. But on the order page "Downloadable Product Permission" panel can not be hidden. It has to show. Because an order can have a downloadable product.

So the issue is invalid.
