### ISSUE TITLE
Withdrawal reverse

### ISSUE THREAD

**Issue by Ditskys** [weDevsOfficial/dokan#1445]
If customer opts to pay on delivery (COD) then the admin fee is missed from equation.. there needs to be a way to flag to admin that this cost needs to be claimed.
This is available on WCFM as below
https://wclovers.com/knowledgebase/wcfm-marketplace-reverse-withdrawal/

I don't want a subscription model. I want to be able to flag to a vendor that they owe an amount for the sale and it's either taken from their withdrawal pot or they can pay it off.

**Comment by nurul-umbhiya** [comment]
This feature is already in our roadmap, will be available soon.

**Comment by Ditskys** [comment]
That's good news! Is the roadmap available to view?

**Comment by nurul-umbhiya** [comment]
@Ditskys No

**Comment by becste** [comment]
> @Ditskys No

what is the timeline behind it? This topic has come up multiple times before 

@nurul-umbhiya in the last one the topic was to not have a positive balance due to CoD but also it didnt implement what was asked for in 1220. Is 1220 the same now as this feature request? I would really love to see this implemented and if you could share details on when it will be available or how soon would be great.

https://github.com/weDevsOfficial/dokan/issues/1220
https://github.com/weDevsOfficial/dokan/issues/34
