### ISSUE TITLE
dokan social login issue error 500

### ISSUE THREAD

**Issue by mohamadhegazy** [weDevsOfficial/dokan#232]
1- valid error 500 issue appeared when tried to login with social media 

it appears also if the user cancel the login via social media 

it happens fresh wordpress 4.9.5 and dokan 2.7.8 and pro 2.7.5 and reported to support team and they validate it

2- also if disabled dokan social login it still conflict with woo-commerce social login 2.4.1

**Comment by mohamadhegazy** [comment]
2- this is happening because you declared Hybrid_Auth class in the main dokan-pro.php and in libs also

i changed all Hybrid_Auth to Hybrid_Auth2 in all pro plugin files and the issue solved so i can use another social login plugin, but issue number 1 is still exist.

i think if you gonna implement social login for pro users by default, you have to use another class name as all social login plugins uses the same class, and we as pro or business users  we have the right to use your plugin and still uses our own if some of us wishes, specially when there's an issue with yours, as wedevs dosn't issue updates that fast, and we cant edit the same files over and over each time there's an update
thank you

**Comment by itsachalsingh** [comment]
Hello wedevs

when you resolve this. I am also getting the same error

Thank you

**Comment by shabnam611** [comment]
Hello,

Dokan social login is a pro version feature. So, please create support ticket and report your issue with screenshot, so that our support team can take a look at your issues.

On March 2018, FaceBook has brought some changes, which made us to fix those issues with Facebook for dokan social login. The latest version of Dokan pro is 2.8.3 and the latest version of Dokan lite is 2.8.5. 

Please make sure you are using the latest version of Dokan lite and Dokan pro. 

Thanks!
