### ISSUE TITLE
REST API Error 401

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#282]
I'm keep on getting this error 401 message: "Sorry you are not allowed to do that" whenever try to get the products, coupons, orders and few other end points. It works fine for getting store data. I'm passing in the credentials as requested by the documentation.
My wordpress well equipped with Basic Auth. If the authentication is the issue, is there any way to get data without authentication? 

You may see the output from picture below: -
https://scontent.fkul8-1.fna.fbcdn.net/v/t1.15752-9/33146732_1312692552199177_6584086316743393280_n.png?_nc_cat=0&oh=ad912e83763236ccf5b2cdfcfd26cf3b&oe=5BC0B02A

**Comment by saimonh3** [comment]
@ManigandanRaamanathan I've tested and found no such issue. Thanks

**Comment by ManigandanRaamanathan** [comment]
@saimonh3  I'm using http site under aws. Will there be a problem if use http site instead of https. Any other alternative?

**Comment by Jehanzeb-Malik** [comment]
In case someone else is having this issue, and they are running an apache server, it might be because sometimes apache strips the authorization header. Add the following to .htaccess to fix it:
`RewriteCond %{HTTP:Authorization} ^(.*)
# Don't know why, but some need the line below instead of the RewriteRule line
# SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`
