### ISSUE TITLE
Cash on Delivery shouldn't increase vendors available money

### ISSUE THREAD

**Issue by Sophivorus** [weDevsOfficial/dokan#34]
If a customer decides to buy a product through the Cash on Delivery payment gateway, then the vendor will receive the money directly from the customer. Therefore, adding that money to the vendors available money makes no sense and could lead to trouble if the vendor asks to withdraw it.

**Comment by rafsuntaskin** [comment]
By default Cash on Delivery is handled by MarketPlace admin therefore the money is added to seller as Customer pays whole money to MarketPlace. After that admin will distribute the money whenever the seller withdraws.

But if you want the sellers to handle COD in that case the admin has no way to collect commissions that's why this is not handled in Dokan that way.

**Comment by Sophivorus** [comment]
So by default, Dokan assumes that the marketplace admin must deliver the products of the vendors, and thus receive the money from the customer? Is that a reasonable assumption?
Remember that COD means: the customer pays in cash when the product is delivered. So if the vendor delivers the product, then the vendor receives the cash. I think the most reasonable assumption is that the vendor will deliver the product. That's the one of the main differences between a marketplace and a regular WooCommerce store. Correct?

**Comment by rafsuntaskin** [comment]
How do you plan to take commission with COD option? As I have said before it really varies from people to people on how they implement their system we are not binding them to anything yet. If we get request for a feature from many users then we will definitely put it in the system.

**Comment by Sophivorus** [comment]
In my marketplace, if a vendor doesn't give me the commission, their account will get blocked.

You say you're not binding us to anything. But currently, if a vendor sells a product by COD and delivers it, I have to manually edit the database to deduce the available money from the vendors account, so that s/he doesn't try to withdraw it!

**Comment by Tangol** [comment]
@alamgircsebd @nurul-umbhiya Guys, any news on this?
It's been 4 years since this report and still no attention to **COD**. People keep asking: https://github.com/weDevsOfficial/dokan/issues/837 , https://github.com/weDevsOfficial/dokan/issues/1220

Over 60% of our orders are using COD and we really need this to be able to take commissions from vendors.

**Comment by nurul-umbhiya** [comment]
@Mohaiminulislam1989 bhai we need to discuss this issue and I think we need to include this on our next sprint.

**Comment by vincebuck** [comment]
@Tangol It is funny because the biggest competitor WCFM has this feature for months already and in Dokan it is still not available, allthough people are asking for it since 4 years. I asked on the wordpress plugin support from weDevs and got the answer to use subscriptions to get "commission" on cod payments.

**Comment by vincebuck** [comment]
@nurul-umbhiya when will this next sprint be? and what would you say will it be in the pro version or in the lite aswell?

**Comment by Tangol** [comment]
@nurul-umbhiya Does @Mohaiminulislam1989 still work with you guys, as I haven't seen him have any activity since January?
The scary thing is that he's assigned to over 13 pretty important tasks...

**Comment by nurul-umbhiya** [comment]
Has been solved
