### ISSUE TITLE
Problem add image gallery woodmart theme

### ISSUE THREAD

**Issue by mr-kofeiti** [weDevsOfficial/dokan#801]
adding Image Gallery and icons are not showing.

**Comment by nayemDevs** [comment]
Hello @mr-kofeiti,

I have checked with the default WordPress theme and the gallery and icons are working fine. WoodMart is a Dokan compatible theme as they tagged Dokan on their ThemeForest page. Did you try to contact them? Because we have changed many things on our latest lite and paid version. So, please contact them to get the best feedback.

**Comment by mr-kofeiti** [comment]
yes. After New Update On woodmart theme and dokan, the problem was solved
