### ISSUE TITLE
Product Not assigned to vendor through rest api

### ISSUE THREAD

**Issue by sarveshamrit** [weDevsOfficial/dokan#823]
Hello , i am using https://codecanyon.net/item/ultimatepos-to-woocommerce-addon-with-saas-compatible/22874559 to sync order from pos system to woocommerce multivendor using dokan, everything works fine but when products is being synced through rest api to the particular vendor that product is not getting assigned to vendor on woocommerce end it remains unassigned to any of vendor. How can we make this happen?

**Comment by zamandevs** [comment]
Currently, we are not supporting assign product to vendor through REST API. will be available in future.

**Comment by sabbir1991** [comment]
Hello, this is not possible from our end. You need to contact the UltimatePOS to WooCommerce Addon plugin author to do the vendor assign process. Because when UltimatePOS sync woocommerce product via rest API, they need to filter products author id as vendors and assign manually when the sync process starts.
